name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3

        with:
          install_command: npm ci
          build_command: npm run build-storybook
          path: storybook-static
          checkout: true
